version: '4'
services:
  mysql:
    image: mysql:latest
    container_name: gas_stations
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gas_stations
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./db/Gas_station.sql:/docker-entrypoint-initdb.d/Gas_station.sql"
      - ./my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
